//
// Created by tadeze on 9/26/17.
//

#ifndef PYIFOREST_GLOBALS_HPP
#define PYIFOREST_GLOBALS_HPP
#define SERIALIZATION true

enum OUTPUT_FORMAT {
    JSON_FORMAT, BINARY_FORMAT
};
double const MISSING_VALUE = -9999.0;
int const NULL_TREE_CHILD_DEPTH = -999;

#endif //PYIFOREST_GLOBALS_HPP
